export enum Page {
  Profile = '/',
  Login = '/login',
  Users = '/users',
  User = '/users/:id',
  Companies = '/companies',
  Company = '/companies/:id',
  Banks = '/banks',
  Bank = '/banks/:id',
  BankCreate = '/banks/create',
  Cashbacks = '/cashback',
  Cashback = '/cashback/:id',
  Discounts = '/discounts',
  Discount = '/discount/:id',
}
